import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Search, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { apiRequest } from '../lib/api'
import type { Customer, MembershipTier, Paginated } from '../types/admin'

const money=new Intl.NumberFormat('en-NP',{style:'currency',currency:'NPR',maximumFractionDigits:0})
export function CustomersPage(){const[search,setSearch]=useState('');const[sort,setSort]=useState('current_year_spend_desc');const[tier,setTier]=useState('');const query=new URLSearchParams({limit:'30',sort});if(search.trim())query.set('search',search.trim());if(tier==='none')query.set('membershipStatus','none');else if(tier)query.set('membershipTierId',tier);const customers=useQuery({queryKey:['admin-customers',query.toString()],queryFn:()=>apiRequest<Paginated<Customer>>('/api/v1/admin/customers?'+query)});const tiers=useQuery({queryKey:['membership-tiers'],queryFn:()=>apiRequest<{data:MembershipTier[]}>('/api/v1/admin/membership-tiers')});return <main className="admin-page"><header className="admin-page-head"><div><p>CUSTOMER RELATIONSHIPS</p><h1>CUSTOMERS</h1><span>Profiles, member status, and spend in the current membership year.</span></div></header><div className="admin-toolbar"><form onSubmit={e=>e.preventDefault()}><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, phone, or email"/><button>Search</button></form><select value={sort} onChange={e=>setSort(e.target.value)}><option value="current_year_spend_desc">Year spend: high to low</option><option value="lifetime_spend_desc">Lifetime spend: high to low</option><option value="membership_rank_desc">Membership tier</option><option value="name_asc">Name: A–Z</option></select><select value={tier} onChange={e=>setTier(e.target.value)}><option value="">All membership states</option><option value="none">No active tier</option>{tiers.data?.data.filter(x=>x.isActive).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div><section className="admin-data-table customer-table"><div className="admin-table-head"><span>Customer</span><span>Membership</span><span>Year spend</span><span>Lifetime spend</span><span></span></div>{customers.isLoading?<div className="admin-loading">Loading customer profiles…</div>:customers.data?.data.length?customers.data.data.map(c=><Link to={`/customers/${c.id}`} key={c.id}><span><strong>{c.fullName}</strong><small>{c.normalizedPhone} · {c.normalizedEmail}</small></span><span>{c.tierName?<em className="admin-status active">{c.tierName} · {c.discountPercent}%</em>:<em className="admin-status neutral">Not activated</em>}</span><strong>{money.format(Number(c.eligibleNetSpend))}</strong><strong>{money.format(Number(c.lifetimeNetSpend))}</strong><span>›</span></Link>):<div className="admin-empty compact"><Users/><h2>No customers found</h2><p>Try a broader search or another filter.</p></div>}</section></main>}
