import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, Check, ExternalLink, MapPin, PackageCheck, ShieldCheck, Truck, X } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { toast } from 'sonner'
import { apiRequest } from '../lib/api'
import type { AdminOrder } from '../types/admin'

const transitions: Record<AdminOrder['status'], AdminOrder['status'][]> = { pending:['cancelled'], confirmed:['packed'], packed:['shipped'], shipped:['delivered'], delivered:[], cancelled:[] }
const amount = (value: string | number | null | undefined) => 'Rs. ' + Number(value ?? 0).toLocaleString()

export function OrderDetailPage() {
  const { id='' } = useParams(); const client = useQueryClient()
  const [trackingRef,setTrackingRef] = useState(''); const [pickupBranch,setPickupBranch] = useState(''); const [destinationBranch,setDestinationBranch] = useState(''); const [weightGrams,setWeightGrams] = useState('500')
  const order = useQuery({queryKey:['admin-order',id],queryFn:async()=> (await apiRequest<{data:AdminOrder}>('/api/v1/admin/orders/'+id)).data})
  const refresh=()=>client.invalidateQueries({queryKey:['admin-order',id]})
  const verify=useMutation({mutationFn:(action:'confirm'|'reject')=>apiRequest('/api/v1/admin/orders/'+id+'/verify-payment',{method:'PATCH',body:JSON.stringify({action})}),onSuccess:(_,action)=>{refresh();toast.success(action==='confirm'?'Payment confirmed and stock updated':'Payment proof rejected')},onError:(error:Error)=>toast.error(error.message)})
  const status=useMutation({mutationFn:(next:AdminOrder['status'])=>apiRequest('/api/v1/admin/orders/'+id+'/status',{method:'PATCH',body:JSON.stringify({status:next,...(next==='shipped'&&trackingRef?{trackingRef}:{})})}),onSuccess:()=>{refresh();toast.success('Order status updated')},onError:(error:Error)=>toast.error(error.message)})
  const book=useMutation({mutationFn:()=>apiRequest('/api/v1/admin/orders/'+id+'/shipment/ncm',{method:'POST',body:JSON.stringify({...(pickupBranch.trim()?{pickupBranch:pickupBranch.trim()}:{}),destinationBranch:(destinationBranch.trim()||data?.shippingBranch)??undefined,weightGrams:Number(weightGrams),deliveryType:'Door2Door'})}),onSuccess:()=>{refresh();toast.success('Nepal Can Move shipment booked')},onError:(error:Error)=>toast.error(error.message)})
  const refund = useMutation({
    mutationFn: (action: 'request' | 'complete') => apiRequest('/api/v1/admin/orders/' + id + '/refund', {
      method: 'PATCH',
      body: JSON.stringify({ action, ...(action === 'request' ? { reason: 'Manual COD advance refund' } : {}) }),
    }),
    onSuccess: (_, action) => { refresh(); toast.success(action === 'request' ? 'Refund task created. Return the advance manually, then mark it completed.' : 'Manual refund recorded as completed') },
    onError: (error: Error) => toast.error(error.message),
  })
  if(order.isPending)return <div className="admin-loading">Loading order…</div>
  if(!order.data)return <div className="admin-empty"><h2>ORDER NOT FOUND</h2><Link to="/orders">Return to orders</Link></div>
  const data=order.data; const payment=data.payments[0]; const shipment=data.shipment
  const paymentLabel = data.paymentMethod === 'cod' ? 'COD — QR advance' : 'Full payment — QR'
  return <main className="admin-page order-detail-admin">
    <Link className="admin-back" to="/orders"><ArrowLeft/>Website orders</Link>
    <header className="admin-page-head"><div><p>{new Date(data.createdAt).toLocaleString()}</p><h1>{data.orderNumber}</h1><span>{data.items?.length??0} items · {data.user?'Customer account':'Guest checkout'} · {paymentLabel}</span></div><div className="order-head-status"><em className={'admin-status '+data.paymentStatus}>{data.paymentStatus}</em><em className={'admin-status '+data.status}>{data.status}</em></div></header>
    <div className="admin-two-column order-detail-grid">
      <section className="admin-panel"><header><h2>Order items</h2><strong>{amount(data.total)}</strong></header><div className="order-item-list">{data.items?.map(item=><article key={item.id}>{item.productImageUrl?<img src={item.productImageUrl} alt=""/>:<span className="item-placeholder">R</span>}<div><strong>{item.productName}</strong><small>{item.variantSku} · {item.variantSize} / {item.variantColor}</small></div><span>{item.qty} × {amount(item.price)}</span></article>)}</div><div className="order-totals"><p><span>Subtotal</span><strong>{amount(data.subtotal)}</strong></p><p><span>Membership</span><strong>{data.membershipTierSnapshot?.name??'No membership'} · {Number(data.membershipDiscountPercent)}%</strong></p><p><span>Member discount</span><strong>−{amount(data.merchandiseDiscount)}</strong></p><p><span>NCM delivery fee</span><strong>{amount(data.shippingDeliveryFee)}</strong></p><p><span>NCM pickup charge</span><strong>{amount(data.shippingPickupFee)}</strong></p><p><span>Shipping total</span><strong>{amount(data.shippingFee)}</strong></p><p><span>Total</span><strong>{amount(data.total)}</strong></p>{data.paymentMethod==='cod'&&<><p><span>Merchandise advance · {Number(data.codMerchandiseAdvancePercent)}%</span><strong>{amount(Math.max(0, Number(data.advancePaymentAmount)-Number(data.shippingFee)))}</strong></p><p><span>QR advance paid now</span><strong>{amount(data.advancePaymentAmount)}</strong></p><p><span>NCM collection</span><strong>{amount(data.codCollectionAmount)}</strong></p></>}</div></section>
      <aside className="order-detail-side">
        <section className="admin-panel"><header><h2>Payment review</h2><ShieldCheck/></header>{payment?<div className="payment-review"><p><span>Checkout method</span><strong>{paymentLabel}</strong></p><p><span>Status</span><em className={'admin-status '+payment.status}>{payment.status.replace('_',' ')}</em></p><p><span>Expected amount</span><strong>{amount(payment.amount)}</strong></p>{data.paymentMethod === 'cod' && <p><span>Collect on delivery</span><strong>{amount(data.codCollectionAmount)}</strong></p>}{payment.screenshotUrl?<a href={payment.screenshotUrl} target="_blank" rel="noreferrer"><img src={payment.screenshotUrl} alt="Customer payment proof"/><span>Open original <ExternalLink/></span></a>:<div className="no-proof">No payment proof uploaded.</div>}{payment.status==='pending_verification'&&<div className="payment-actions"><button className="admin-danger" disabled={verify.isPending} onClick={()=>verify.mutate('reject')}><X/>Reject</button><button className="admin-primary" disabled={verify.isPending} onClick={()=>verify.mutate('confirm')}><Check/>Confirm</button></div>}</div>:<p>No payment attempt recorded.</p>}</section>
        <section className="admin-panel"><header><h2>Fulfilment</h2><PackageCheck/></header><div className="status-progress">{['pending','confirmed','packed','shipped','delivered'].map((step,index)=><span className={['pending','confirmed','packed','shipped','delivered'].indexOf(data.status)>=index?'done':''} key={step}>{step}</span>)}</div>{data.status==='packed'&&!shipment&&<label className="tracking-input"><span>Manual tracking reference (optional)</span><input value={trackingRef} onChange={event=>setTrackingRef(event.target.value)}/></label>}<div className="next-status">{transitions[data.status].map(next=><button key={next} className={next==='cancelled'?'admin-danger':'admin-primary'} onClick={()=>status.mutate(next)} disabled={status.isPending}>Mark {next}</button>)}</div></section>
        <section className="admin-panel"><header><h2>Nepal Can Move</h2><Truck/></header>{shipment?<div className="payment-review"><p><span>Booking</span><em className="admin-status active">{shipment.bookingStatus}</em></p><p><span>Tracking</span><strong>{shipment.carrierOrderId??'Pending'}</strong></p><p><span>Carrier status</span><strong>{shipment.carrierStatus??'Awaiting pickup'}</strong></p>{shipment.bookingError&&<p>{shipment.bookingError}</p>}<div className="status-progress">{shipment.events.map(event=><span className="done" key={event.event+'-'+event.receivedAt}>{event.status}</span>)}</div></div>:data.status==='packed'?<div className="guest-grid"><label><span>Pickup branch</span><input placeholder="Store default" value={pickupBranch} onChange={event=>setPickupBranch(event.target.value.toUpperCase())}/></label><label><span>Destination branch{data.shippingBranch?' (chosen by customer)':''}</span><input required placeholder={data.shippingBranch??'NCM branch name'} value={destinationBranch} onChange={event=>setDestinationBranch(event.target.value.toUpperCase())}/></label><label><span>Weight (grams)</span><input type="number" min="1" value={weightGrams} onChange={event=>setWeightGrams(event.target.value)}/></label><button className="admin-primary" disabled={book.isPending||!(destinationBranch.trim()||data.shippingBranch)} onClick={()=>book.mutate()}>Book NCM delivery</button></div>:<p>Verify payment, then pack the parcel before booking NCM.</p>}</section>
        <section className="admin-panel"><header><h2>COD refund</h2><ShieldCheck/></header>{data.paymentMethod!=='cod'?<p>POS and full QR payments are strictly non-refundable.</p>:data.refundStatus?<div className="payment-review"><p><span>Status</span><em className={'admin-status '+(data.refundStatus==='completed'?'active':'pending_verification')}>{data.refundStatus}</em></p><p><span>Refund amount</span><strong>{amount(data.refundAmount)}</strong></p><p><span>Reason</span><strong>{data.refundReason}</strong></p>{data.refundStatus==='pending'&&<button className="admin-primary" disabled={refund.isPending} onClick={()=>refund.mutate('complete')}><Check/>Mark manual refund completed</button>}</div>:<div className="payment-review"><p>Allowed before NCM booking, or after NCM confirms the parcel has returned to the warehouse.</p><p><span>Advance to return</span><strong>{amount(data.advancePaymentAmount)}</strong></p><button className="admin-danger" disabled={data.paymentStatus!=='paid'||refund.isPending} onClick={()=>refund.mutate('request')}>Create manual refund task</button></div>}</section>
        <section className="admin-panel"><header><h2>Delivery</h2><MapPin/></header><address><strong>{data.user?.name??data.guestName}</strong><span>{data.guestPhone||data.user?.phone}</span><span>{data.guestFullAddress}</span><span>{data.guestCity}</span></address></section>
      </aside>
    </div>
  </main>
}
