import { useState } from 'react'
import { Boxes, Cake, ChartNoAxesCombined, ChevronRight, ClipboardList, FolderTree, LogOut, Menu, PackageSearch, QrCode, ScanLine, ShieldAlert, UserCog, Users, X } from 'lucide-react'
import { NavLink, Outlet, useLocation } from 'react-router-dom'
import { authClient } from '../lib/auth-client'

const nav=[{to:'/',label:'Sales',icon:ChartNoAxesCombined},{to:'/products',label:'Products',icon:Boxes},{to:'/categories',label:'Categories',icon:FolderTree},{to:'/stock',label:'Stock & audit',icon:PackageSearch},{to:'/orders',label:'Web sales & shipping',icon:ClipboardList},{to:'/payment-settings',label:'Payment QR',icon:QrCode},{to:'/pos-sales',label:'POS sales',icon:ScanLine},{to:'/customers',label:'Customers',icon:Users},{to:'/birthdays',label:'Birthdays',icon:Cake},{to:'/membership-tiers',label:'Membership tiers',icon:ShieldAlert},{to:'/staff',label:'Staff',icon:UserCog}]

export function RequireAdmin(){const{data:session,isPending}=authClient.useSession();if(isPending)return <div className="admin-gate">Checking administrator access…</div>;if(!session){window.location.replace('/login');return null}const role=(session.user as{role?:string}).role;if(role!=='admin')return <div className="admin-gate"><ShieldAlert/><h1>ADMIN ACCESS REQUIRED.</h1><p>This session is authenticated but does not have the Admin role.</p><button onClick={()=>authClient.signOut().then(()=>window.location.replace('/login'))}>Use another account</button></div>;return <AdminLayout/>}

function AdminLayout(){const[open,setOpen]=useState(false);const{data:session}=authClient.useSession();const location=useLocation();const title=nav.find((item)=>item.to==='/'?location.pathname==='/':location.pathname.startsWith(item.to))?.label??'Administration';const user=session?.user as{name?:string;email?:string}|undefined;const links=nav.map(({to,label,icon:Icon})=><NavLink end={to==='/'} to={to} key={to} onClick={()=>setOpen(false)}><Icon/><span>{label}</span><ChevronRight/></NavLink>);return <div className="admin-shell"><aside className={`admin-sidebar ${open?'open':''}`}><header><a href="/"><i className="brand-star" aria-hidden="true" />ROGUEON<span>ADMIN</span></a><button onClick={()=>setOpen(false)}><X/></button></header><nav>{links}</nav><footer><div><span>{user?.name?.slice(0,1).toUpperCase()}</span><p>{user?.name}<small>{user?.email}</small></p></div><button aria-label="Sign out" onClick={()=>authClient.signOut().then(()=>window.location.replace('/login'))}><LogOut/></button></footer></aside>{open&&<button className="admin-backdrop" aria-label="Close menu" onClick={()=>setOpen(false)}/>}<section className="admin-workspace"><header className="admin-topbar"><button className="admin-menu" onClick={()=>setOpen(true)}><Menu/></button><div><span>ROGUEON / ADMINISTRATION</span><strong>{title}</strong></div><a href="/orders?pending=true">Payment queue <ShieldAlert/></a></header><Outlet/></section></div>}
